drop table if exists babel_extension_language_proficiences;
drop table if exists babel_extension_user_languages;
drop table if exists cx_translations;
drop table if exists normalized_proficiencies;
drop table if exists translation_revisions;
drop table if exists translators;
drop table if exists translator_user_pages;
drop table if exists user_page_language_proficiencies;
drop table if exists wikipedia_languages;
